FROM openjdk:17

ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG CLIENT_ID
ARG CLIENT_SECRET
ARG REDIRECT_URI
ARG JWT_SECRET
ARG JWT_VALIDITY_TIME

ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV CLIENT_ID=${CLIENT_ID}
ENV CLIENT_SECRET=${CLIENT_SECRET}
ENV REDIRECT_URI=${REDIRECT_URI}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_VALIDITY_TIME=${JWT_VALIDITY_TIME}

ARG JAR_FILE_PATH=build/libs/*.jar
COPY ${JAR_FILE_PATH} Magnet-0.0.1.jar

COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

CMD /wait-for-it.sh localhost:3306 --timeout=30 -- java -jar Magnet-0.0.1.jar